### ISSUE TITLE
Segfault when turning stutter on

### ISSUE THREAD

**Issue by kjyv** [mtytel/helm#140]
I've only tested this on ARM (so referring also to #75), but with current development branch, turning on stutter crashes helm (as lv2 plugin) every time.

**Comment by kjyv** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x6e04e450 (LWP 10439)]
0x7005c8d8 in mopo::VoiceHandler::writeNonaccumulatedOutputs (this=this@entry=0x7cd9b0) at ../../../mopo/src/voice_handler.cpp:121
121           mopo_float* dest = output.second->buffer;
(gdb) bt
#0  0x7005c8d8 in mopo::VoiceHandler::writeNonaccumulatedOutputs (this=this@entry=0x7cd9b0) at ../../../mopo/src/voice_handler.cpp:121
#1  0x7005e764 in mopo::VoiceHandler::process (this=0x7cd9b0) at ../../../mopo/src/voice_handler.cpp:168
#2  0x7003be38 in mopo::HelmVoiceHandler::process (this=0x7cd8b0) at ../../../src/synthesis/helm_voice_handler.cpp:750
#3  0x70051218 in mopo::ProcessorRouter::process (this=0x7a7434) at ../../../mopo/src/processor_router.cpp:82
#4  0x7002ce88 in mopo::HelmEngine::process (this=this@entry=0x7a7318) at ../../../src/synthesis/helm_engine.cpp:362
#5  0x700753d8 in SynthBase::processAudio (this=0x6e04d9c4, this@entry=0x7a7300, buffer=buffer@entry=0x6e04da64, channels=channels@entry=2,
    samples=samples@entry=128, offset=offset@entry=0) at ../../../src/common/synth_base.cpp:226
#6  0x70029c14 in HelmPlugin::processBlock (this=0x7a7300, buffer=..., midi_messages=...) at ../../../src/plugin/helm_plugin.cpp:183
#7  0x6fd65f68 in JuceLv2Wrapper::lv2Run (this=0x7a6d18, sampleCount=70136)
    at ../../../JUCE/modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper.cpp:1579
#8  0x0001735c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

**Comment by mtytel** [comment]
Oh shoot yeah I just broke it. Working on a fix

**Comment by mtytel** [comment]
Cleaned it up and fixed it. Should work now.
Will test it more later.
